server:
  port: 9093

eureka:
  client:
    fetch-service-url:
      defaultZone: http://localhost:8761/

spring:
  application:
    name: FOOD-CATALOG-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    datasource-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/food
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
service:
  url:
    restaurant: http://RESTAURANT-SERVICE/
    user: http://USER-SERVICE/